export { default as Audio } from './small/Audio.svelte'
export { default as Close } from './small/Close.svelte'
export { default as Coin } from './small/Coin.svelte'
export { default as Down } from './small/Down.svelte'
export { default as Left } from './small/Left.svelte'
export { default as LeftArrows } from './small/LeftArrows.svelte'
export { default as Nib } from './small/Nib.svelte'
export { default as PaginationDot } from './small/PaginationDot.svelte'
export { default as Pause } from './small/Pause.svelte'
export { default as Play } from './small/Play.svelte'
export { default as Right } from './small/Right.svelte'
export { default as RightArrows } from './small/RightArrows.svelte'

export { default as SmallIcon } from './SmallIcon.svelte'
