export { default as ArrowLogo } from './ArrowLogo.svelte'
export { default as Button } from './Button.svelte'
export { default as Carousel } from './Carousel.svelte'
export { default as FeaturedProjects } from './FeaturedProjects.svelte'
export { default as Flex } from './Flex.svelte'
export { default as FullScreenVideo } from './FullScreenVideo.svelte'
export { default as Gallery } from './Gallery.svelte'
export { default as Modal } from './Modal.svelte'
export { default as Text } from './Text.svelte'
export { default as Video } from './Video.svelte'

export { default as Heading2 } from './text/Heading2.svelte'
export { default as Heading3 } from './text/Heading3.svelte'
export { default as Heading4 } from './text/Heading4.svelte'
export { default as Paragraph } from './text/Paragraph.svelte'
